MvcAuction/MvcAuction/Controllers/AuctionsController.cs
using MvcAuction.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MvcAuction.Controllers
{
    public class AuctionsController : Controller
    {
        //
        // GET: /Auctions/

        [AllowAnonymous]
        [OutputCache(Duration = 1)]
        public ActionResult Index()
        {
            var db = new AuctionsDataContext();
            var auctions = db.Auctions.ToArray();

            return View(auctions);
        }

        [OutputCache(Duration = 10)]
        public ActionResult Auction(long id)
        {
            var db = new AuctionsDataContext();
            var auction = db.Auctions.Find(id);

            return View(auction);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Bid(Bid bid)
        {
            var db = new AuctionsDataContext();
            var auction = db.Auctions.Find(bid.AuctionId);

            if (auction == null)
            {
                ModelState.AddModelError("AuctionId", "Auction not found!");
            }
            else if (auction.CurrentPrice >= bid.Amount)
            {
                ModelState.AddModelError("Amount", "Bid amount must exceed current bid");
            }
            else
            {
                bid.Username = User.Identity.Name;
                auction.Bids.Add(bid);
                auction.CurrentPrice = bid.Amount;
                db.SaveChanges();
            }

            if(!Request.IsAjaxRequest())
                return RedirectToAction("Auction", new { id = bid.AuctionId });

            return Json(new {
                CurrentPrice = bid.Amount.ToString("C"),
                BidCount = auction.BidCount
            });
        }


        [HttpGet]
        public ActionResult Create()
        {
            var categoryList = new SelectList(new[] { "Automotive", "Electronics", "Games", "Home" });
            ViewBag.CategoryList = categoryList;
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult Create([Bind(Exclude="CurrentPrice")]Models.Auction auction)
        {
            if (ModelState.IsValid)
            {
                // Save to the database
                var db = new AuctionsDataContext();
                db.Auctions.Add(auction);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
                
            return Create();
        }
    }
}

MvcAuction/MvcAuction/Views/Auctions/Auction.cshtml
@model MvcAuction.Models.Auction
@{
    var auction = Model;
}

@Html.ActionLink("Login", "Login", "Account")

<div class="auction">

    <h3>@auction.Title</h3>

    <div class="details">
       <p>Start Time: @auction.StartTime.ToString("g")</p>
       <p>End Time: @auction.EndTime.ToString("g")</p>
       <p>Starting Price: @auction.StartPrice.ToString("C")</p>
       <p class="current-price">Current Price:
           @*
               Since CurrentPrice is nullable we have to check to
               see if it has a value before we call .ToString()!
           *@
           @if(auction.CurrentPrice == null)
           {
               <text>
               [No bids]
               </text>
           }
           else
           {
               <span>@auction.CurrentPrice.Value.ToString("C")</span>
               <span>[@auction.BidCount bids]</span>
           }
       </p>
        <p>
            @using (Html.BeginForm("Bid", "Auctions"))
            {
                var lowestBidAmount = auction.CurrentPrice.GetValueOrDefault(auction.StartPrice) + 1;
                <span>
                    Bid: $@Html.TextBox("amount", lowestBidAmount)
                    @Html.ValidationMessage("amount")
                </span>
                
                @Html.Hidden("auctionId", auction.Id)

                @Html.AntiForgeryToken()

                <input class="post-bid" type="submit" value="Bid" />
            }
        </p>
    </div>

    @if(auction.ImageUrl != null) {
       <img src="@auction.ImageUrl" title="@auction.Title" />
    }

    <div class="description">
       @auction.Description
    </div>

</div>

<span>Last rendered: @DateTime.Now</span>

<script id="current-price-template" type="application/html-template">
    <p class="current-price">
        <span>Current Price: {{CurrentPrice}}</span>
        <span>[{{BidCount}} bids]</span>
    </p>
</script>



@section Scripts {
    <script type="text/javascript">
        $(function () {
            $('.post-bid').on("click", function () {

                var form = $(this).parent("form");

                $.ajax({
                    type: "POST",
                    url: form.attr('action'),
                    data: form.serialize()
                })
                    .success(function (data) {
                        var template = $('#current-price-template').clone().html();

                        var html =
                            template
                                .replace('{{CurrentPrice}}', data.CurrentPrice)
                                .replace('{{BidCount}}', data.BidCount);

                        $('.current-price').replaceWith(html);
                    })
                    .error(function () {
                        alert("Your bid has been rejected");
                    });

                return false;
            });
        });
    </script>
}

MvcAuction/MvcAuction/Views/Auctions/Create.cshtml
@model MvcAuction.Models.Auction

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Auction</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Category)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.Category, (SelectList)ViewBag.CategoryList)
            @Html.ValidationMessageFor(model => model.Category)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ImageUrl)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ImageUrl)
            @Html.ValidationMessageFor(model => model.ImageUrl)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.StartTime)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.StartTime)
            @Html.ValidationMessageFor(model => model.StartTime)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.EndTime)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.EndTime)
            @Html.ValidationMessageFor(model => model.EndTime)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.StartPrice)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.StartPrice)
            @Html.ValidationMessageFor(model => model.StartPrice)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcAuction/MvcAuction/Views/Auctions/Index.Mobile.cshtml
@model IEnumerable<MvcAuction.Models.Auction>

@{
    ViewBag.Title = "Auctions: Mobile View";
    DisplayModeProvider.Instance.RequireConsistentDisplayMode = true;
}

@section Scripts {
    <!-- This content will be rendered in the Scripts section -->
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@foreach (var item in Model) {
    @Html.Partial("_AuctionTile", item)
}

MvcAuction/MvcAuction/Views/Auctions/Index.cshtml
@model IEnumerable<MvcAuction.Models.Auction>

@{
    Layout = "~/Views/Shared/_LayoutWithSidebar.cshtml";
    ViewBag.Title = "Auctions";
}

@section Sidebar {
    <h3>This is my sidebar!</h3>
}

@section Featured {
    <section class="featured">
        <div class="content-wrapper">
            This is some featured content!
        </div>
    </section>
}

@section Scripts {
    <!-- This content will be rendered in the Scripts section -->
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@foreach (var item in Model) {
    @Html.Partial("_AuctionTile", item)
}

MvcAuction/MvcAuction/Views/Auctions/Index.iPad.cshtml
@model IEnumerable<MvcAuction.Models.Auction>

@{
    ViewBag.Title = "Auctions: iPad View";
    DisplayModeProvider.Instance.RequireConsistentDisplayMode = true;
}

@section Scripts {
    <!-- This content will be rendered in the Scripts section -->
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@foreach (var item in Model) {
    @Html.Partial("_AuctionTile", item)
}

MvcAuction/MvcAuction/Views/Auctions/Index.iPhone.cshtml
@model IEnumerable<MvcAuction.Models.Auction>

@{
    ViewBag.Title = "Auctions: iPhone View";
    DisplayModeProvider.Instance.RequireConsistentDisplayMode = true;
}

@section Scripts {
    <!-- This content will be rendered in the Scripts section -->
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@foreach (var item in Model) {
    @Html.Partial("_AuctionTile", item)
}

MvcAuction/MvcAuction/Views/Auctions/_CurrentPrice.cshtml
<p class="current-price">
    <span>Current Price: @Model.CurrentPrice.ToString("C")</span>
    <span>[@Model.BidCount bids]</span>
</p>